### ISSUE TITLE
Handle ModuleReady messages

### ISSUE THREAD

**Issue by dmw109** [dmw109/pyrtma#4]

**Comment by jmw182** [comment]
Working on this. Handling the ModuleReady message and storing pids is simple, but the TimingMessage that is output with these values is larger than the expected message size (See #7).

**Comment by jmw182** [comment]
This is mostly handled by commit f58aa06. We just need a way to send the (currently >9kb) TimingMessage.

**Comment by jmw182** [comment]
Fixed support for large message types and sending TIMING_MESSAGE in d22618a.
